services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  
  backend:
    image: node:20.18-slim
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    ports:
      - 3000:3000

  frontend:
    image: node:20.18-slim
    stdin_open: true # docker run -i #
    tty: true        # docker run -t
    restart: always
    ports:
      - 5000:5000   

  test:
    image: debian
    command: /app/main
    stdin_open: true # docker run -i #
    tty: true        # docker run -t
    restart: always
    ports:
      - 5500:5500 
    volumes:
        - ./app:/app